set-option -g default-command "reattach-to-user-namespace -l /bin/zsh"
set -g default-terminal "tmux-256color"
set -g mode-keys vi
set -g default-shell /bin/zsh

set -g mouse on
# Reload .tmux.conf with prefix-r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g prefix C-u
unbind C-b

set -sg escape-time 0
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'c' send -X copy-selection
bind-key -T copy-mode-vi y  send -X copy-pipe-and-cancel "pbcopy"
bind v run-shell "tmux paste-buffer"

set-option -g history-limit 100000

# quick pane cycling
bind ^u last-pane
unbind ^C-o

# hjkl to navigate panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use current directory for splits
bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

# Keep last pane zoomed
bind -n C-\; last-pane -Z

# Solarized Dark theme
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @colors-solarized 'dark'

### TPM
set -g @plugin 'tmux-plugins/tpm'

##### Session persistence
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

##### Autosave / autorestore
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

##### Neovim integration (important)
set -g @resurrect-strategy-nvim 'session'

# Status line
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{session_name} | %H:%M"

# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
run '~/.tmux/plugins/tpm/tpm'
