---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: 
  - activemodel
  - activerecord
  - chime-service-base
domains: []
reporters:
- require_not_found
require_paths: []
plugins: 
 - solargraph-rails
max_files: 35000
