#! /bin/bash

echo "This will permanently remove Firefox and its data."
read -p "Are you sure? (y/N) " confirm
if [[ "$confirm" != [yY] ]]; then
  echo "Aborted."
  exit 0
fi

rm -rf /Applications/Firefox.app
rm -rf ~/Library/Preferences/org.mozilla.firefox.plist
rm -rf ~/Library/Application\ Support/Firefox

echo 'Firefox uninstalled successfully'
