#!/bin/bash

path=$1
if [ "$path" == "" ]; then
  path=~/dev/dotfiles
fi
echo Switching dotfiles to $path

rm ~/.vim
rm ~/.vimrc
rm ~/.tmux.conf

ln -s $path/.vimrc ~/.vimrc
ln -s $path/.vim ~/.vim
ln -s $path/.tmux.conf ~/.tmux.conf

tmux source-file ~/.tmux.conf

